services:
  odoo:
    build: .
    depends_on:
      - db
      - waha
    ports:
      - "8069:8069"
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo-data:/var/lib/odoo
    environment:
      - PASSWORD=odoo
      - USER=odoo
      - HOST=db
      - PORT=5432
    command: --

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data

  waha:
    # IMAGEM CORRIGIDA AQUI
    image: devlikeapro/waha
    ports:
      - "4000:3000"
    environment:
      # Adicione a sua API Key aqui se o WAHA a exigir
      - WAHA_PLUS_API_KEY=sua-api-key-secreta
    volumes:
      - waha-sessions:/sessions

volumes:
  odoo-data:
  db-data:
  waha-sessions: